export const SENDING = 'Sending'
export const RECEIVED = 'Received'
export const REJECTED = 'Rejected'
export const SUCCESS = 'Success'
export const PROCESS = 'Processing'
export const PROCESSED = 'Processed'
export const FAILED = 'Failed'

export const ORDER_UNPAID = 'Unpaid'
export const ORDER_PAID = 'Paid'
export const ORDER_FULFILLED = 'Fulfilled'
export const ORDER_REFUNDED = 'Refunded'
export const ORDER_CANCEL = 'Cancelled'
export const ORDER_FAILED = 'Failed'
export const ORDER_PROCESSED = 'Processed'
